#
#  This file is part of VoteLogger.
#
#  VoteLogger: A software for logging votes, works with Votifier.
#  Copyright (C) 2018 akaregi <akg.tachibana@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Prefix. You don't have to attach a space to the end.
plugin-prefix: "&8[&6VoteLogger&8]&r"

# Log formatting
# {0}: ISO8601 Time
# {1}: Service name
# {2}: Username
log-format: "[{0}] {1} {2}"

# Logging
log-name: "Votes.log"

# Time difference
log-offset: 9

#   Configuration
# -----------------
#    Translation

# Message for /vl version
# {0}: Version
# {1}: Author name
plugin-version: "&7Version &bv{0}&7, by &b{1}"

# Enabled / Disabled message.
# {0}: Version
plugin-enabled: "&aVoteLogger v{0} has been enabled."
plugin-disabled: "&aVoteLogger v{0} has been disabled. Good bye!"

# Message for those who doesn't have permission
# NOTE: This message DOESN'T include prefix.
permission-insufficient: "&cYou don't have permission."

# Commands
# {0}: Available commands (command-available only)
command-available: "&7Available commands: &b{0}"
command-blank: "&7Please specify arguments."
command-unknown: "&7Unknown command."

# Console log
# {0}: Raw message of Java object "Vote"
console-log-success: "&bLogged a vote: {0}"
console-log-failure: "&cFailed to log a vote: {0}"
