#
#  This file is part of VoteLogger.
#
#  VoteLogger: A software for logging votes,worksworks with Votifier.
#  Copyright (C) 2018 akaregi <akg.tachibana@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

main: com.github.akaregi.votelogger.VoteLogger
name: ${project.artifactId}
version: ${project.version}
description: "Logger for Votifier."
authors: [akaregi]
api-version: "1.13"
depend: [Votifier]

permissions:
  votelogger.admin:
    default: op

commands:
  vl:
    aliases: [votelogger]
    description: "Command for VoteLogger."
    permission: votelogger.admin
    usage: /<command> [args]
